### ISSUE TITLE
Kitematic error

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#41]
When starting paperyard via Kitematic the following error message is thrown

```
Slim Application Error
The application could not run because of the following error:

Details

Type: Error
Message: Call to a member function fetchArray() on boolean
File: /paperyardSrc/paperyard/paperyard/frontend/controllers/views/IndexView.php
Line: 33
Trace

#0 /paperyardSrc/paperyard/paperyard/frontend/controllers/views/IndexView.php(27): Paperyard\Views\IndexView->documentsScanned()
#1 /paperyardSrc/paperyard/paperyard/frontend/src/routes.php(10): Paperyard\Views\IndexView->render()
#2 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(476): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /paperyardSrc/paperyard/paperyard/frontend/public/index.php(30): Slim\App->run()
#12 {main}
```

**Comment by jannik-kramer** [comment]
This should be temporary and self healing. This happens, because the db does not exist in the first seconds of the first startup. I should add some code to check for this.
