### ISSUE TITLE
Error calling up /latest

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#52]
```
Slim Application Error
The application could not run because of the following error:

Details

Type: Howtomakeaturn\PDFInfo\Exceptions\OpenPDFException
File: /paperyardSrc/paperyard/paperyard/frontend/vendor/howtomakeaturn/pdfinfo/src/Howtomakeaturn/PDFInfo/PDFInfo.php
Line: 59
Trace

#0 /paperyardSrc/paperyard/paperyard/frontend/vendor/howtomakeaturn/pdfinfo/src/Howtomakeaturn/PDFInfo/PDFInfo.php(35): Howtomakeaturn\PDFInfo\PDFInfo->loadOutput()
#1 /paperyardSrc/paperyard/paperyard/frontend/models/Document.php(219): Howtomakeaturn\PDFInfo\PDFInfo->__construct('/data/outbox/20...')
#2 /paperyardSrc/paperyard/paperyard/frontend/models/Document.php(152): Paperyard\Models\Document->getNumberOfPages('/data/outbox/20...')
#3 /paperyardSrc/paperyard/paperyard/frontend/controllers/archive/Confirm.php(63): Paperyard\Models\Document->__construct('/data/outbox/20...')
#4 [internal function]: Paperyard\Controllers\Archive\Confirm->Paperyard\Controllers\Archive\{closure}('/data/outbox/20...', 0)
#5 /paperyardSrc/paperyard/paperyard/frontend/controllers/archive/Confirm.php(64): array_walk(Array, Object(Closure))
#6 /paperyardSrc/paperyard/paperyard/frontend/controllers/archive/Confirm.php(48): Paperyard\Controllers\Archive\Confirm->getDocumentsFromPattern('/data/outbox/*....')
#7 /paperyardSrc/paperyard/paperyard/frontend/controllers/archive/Confirm.php(41): Paperyard\Controllers\Archive\Confirm->getOutboxFile()
#8 /paperyardSrc/paperyard/paperyard/frontend/controllers/archive/Confirm.php(33): Paperyard\Controllers\Archive\Confirm->render()
#9 [internal function]: Paperyard\Controllers\Archive\Confirm->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#12 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(479): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /paperyardSrc/paperyard/paperyard/frontend/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /paperyardSrc/paperyard/paperyard/frontend/public/index.php(37): Slim\App->run()
#19 {main}
```

**Comment by tlwt** [comment]
Error is thrown, when webserver does not have read permission on the document
